import { DataTypes, Model } from 'sequelize';
import sequelize from '../config/sequelize.js';

class Program extends Model {}

Program.init(
  {
    programid:                  { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    slug:                       { type: DataTypes.STRING(50) },
    fqdn:                       { type: DataTypes.STRING },
    port:                       { type: DataTypes.INTEGER },
    name:                       { type: DataTypes.STRING },
    portalopen:                 { type: DataTypes.BOOLEAN },
    smtpserver:                 { type: DataTypes.STRING },
    usesimplejudging:           { type: DataTypes.BOOLEAN },
    autolinktolimedb:           { type: DataTypes.BOOLEAN },
    emailfromaddress:           { type: DataTypes.STRING },
    standardhtml:               { type: DataTypes.STRING },
    emailhtml:                  { type: DataTypes.STRING },
    loginhtml:                  { type: DataTypes.STRING },
    mobiletemplate:             { type: DataTypes.STRING },
    loginpagetext:              { type: DataTypes.TEXT },
    admindescriptiontext:       { type: DataTypes.TEXT },
    adminwelcometext:           { type: DataTypes.TEXT },
    judgedescriptiontext:       { type: DataTypes.TEXT },
    judgewelcometext:           { type: DataTypes.TEXT },
    finalistdescriptiontext:    { type: DataTypes.TEXT },
    finalistwelcometext:        { type: DataTypes.TEXT },
    nonfinalistwelcometext:     { type: DataTypes.TEXT },
    standarddescriptiontext:    { type: DataTypes.TEXT },
    standardwelcometext:        { type: DataTypes.TEXT },
    entrytctext:                { type: DataTypes.TEXT },
    judgetctext:                { type: DataTypes.TEXT },
    userhelptext:               { type: DataTypes.TEXT },
    judgehelptext:              { type: DataTypes.TEXT },
    judgecontacttext:           { type: DataTypes.TEXT },
    invoicefromtext:            { type: DataTypes.TEXT },
    invoicenoprecursor:         { type: DataTypes.STRING },
    ewaycustomerno:             { type: DataTypes.STRING },
    ewaygatewayaddress:         { type: DataTypes.STRING },
    paymentinstructionstext:    { type: DataTypes.TEXT },
    remittanceadvicetext:       { type: DataTypes.TEXT },
    receipttext:                { type: DataTypes.TEXT },
    finalistlistbody:           { type: DataTypes.TEXT },
    flfooternoneaccepted:       { type: DataTypes.TEXT },
    flfooterallfinalists:       { type: DataTypes.TEXT },
    flfootersomefinalists:      { type: DataTypes.TEXT },
    flfooternofinalists:        { type: DataTypes.TEXT },
    scoresexplained:            { type: DataTypes.TEXT },
    entriesopendefault:         { type: DataTypes.BOOLEAN },
    paymentsopendefault:        { type: DataTypes.BOOLEAN },
    judgingopendefault:         { type: DataTypes.BOOLEAN },
    scorereadydefault:          { type: DataTypes.BOOLEAN },
    finalistreviewdefault:      { type: DataTypes.BOOLEAN },
    wildcarddecisiondefault:    { type: DataTypes.BOOLEAN },
    winnernominationdefault:    { type: DataTypes.BOOLEAN },
    judgereview:                { type: DataTypes.BOOLEAN },
    headjudgesseefinalists:     { type: DataTypes.BOOLEAN },
    finalistlistavailable:      { type: DataTypes.BOOLEAN },
    nonfinalistscoresavailable: { type: DataTypes.BOOLEAN },
    finalistscoresavailable:    { type: DataTypes.BOOLEAN },
    feedbackopen:               { type: DataTypes.BOOLEAN },
    faveventavailable:          { type: DataTypes.BOOLEAN },
    downloadpagehtml:           { type: DataTypes.TEXT },
    costexplanationtext:        { type: DataTypes.TEXT },
    newusernotification:        { type: DataTypes.STRING },
    judgingmodelid:             { type: DataTypes.INTEGER },
    ccdpaymentonly:             { type: DataTypes.BOOLEAN },
    faviconfile:                { type: DataTypes.STRING },
    entryclosedate:             { type: DataTypes.STRING(30) },
  },
  {
    sequelize,
    modelName: 'Program',
    tableName: 'Program',
    timestamps: false,
  }
);

export default Program;
